Revert "Update maven-project-info-reports-plugin to version 3.0.0 (#334)"
This reverts commit b5b439bc721401dfe4d372366d94fe5b1b6f2b8b.

maven-site-plugin:site fails with
ava.lang.NoClassDefFoundError: org/apache/maven/doxia/siterenderer/DocumentContent