Fix aggregated-java-sources execution (#472)
* No need to remove unrelated-sources ; this is done in a trivial way now

Follow-up of #463

* Run jflex.Main from java directiry

Fix branch failure
```
$ java jflex.Main --version
Error: Could not find or load main class jflex.Main

```