Pseudo-Merge 48787cf Minor: Address Error prone warnings (#749)
commit 48787cf5e02690d54fb3e5251e3a8af52c53c62d
Author:     Régis Décamps <regisd@google.com>
AuthorDate: Sat Mar 28 21:50:42 2020 +0100
Commit:     GitHub <noreply@github.com>
CommitDate: Sat Mar 28 21:50:42 2020 +0100

    Minor: Address Error prone warnings (#749)

    * Exclude all generated code from error-prone.

    * Remove cup from the XepExcludedPaths
    Follow-up of #734

    * Make fields final.
      https://errorprone.info/bugpattern/FieldCanBeFinal

    * Remove reference equality
      https://errorprone.info/bugpattern/ReferenceEquality

    * Keep UnnecessaryParentheses disabled

    ```
    jflex/src/main/java/jflex/generator/Emitter.java:1173: error: [UnnecessaryParentheses] Unnecessary use of grouping parentheses
              println("            case " + (++last) + ": break;");
                                            ^
        (see https://errorprone.info/bugpattern/UnnecessaryParentheses)
      Did you mean 'println("            case " + ++last + ": break;");'?
    ```

    https://errorprone.info/bugpattern/UnnecessaryParentheses

    * Reenable CatchAndPrintStackTrace

    Nothing to fix

    * Fix DefaultCharset
    Also Replace guava Charsets by java StandardCharsets

    https://errorprone.info/bugpattern/DefaultCharset

    LexScan was already fixed in #470

    * Fix ConstructorInvokesOverridable

    make methods final.
    https://errorprone.info/bugpattern/ConstructorInvokesOverridable

    SuppressWarnings for OptionsDialog.java

    * Add default case to switch statements

    https://errorprone.info/bugpattern/MissingDefault

    * Enable Unused  at ERROR

    Suppress warnings on WIP ucd_generator

    https://errorprone.info/bugpattern/Unused

    * Enable UnusedException as ERROR

    Fix violations when possible
    SuppressWarnings otherwise

    https://errorprone.info/bugpattern/UnusedException

    * Keep Var OFF

    it's quite controversial and there are tons of violations.
    https://errorprone.info/bugpattern/Var

    * Fix MixedArrayDimensions

    Rewrite C-style array declaration.

    https://errorprone.info/bugpattern/MixedArrayDimensions

    * Fix MethodCanBeStatic

    https://errorprone.info/bugpattern/MixedArrayDimensions

    * Fix WildcardImport

    List imports  explicitly

    https://errorprone.info/bugpattern/WildcardImport

Updated from target/jflex-parent-1.9.0-SNAPSHOT-sources.jar