Try to compile the core jflex-unicode-maven-plugin
Fails because of stupid import:
```
jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/UnicodeVersion.java:34: error: package org.apache.maven.plugin.logging does not exist
import org.apache.maven.plugin.logging.Log;
                                      ^
jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/UnicodeVersion.java:161: error: cannot find symbol
  public void fetchAndParseDataFiles(Log log) throws IOException {
                                     ^
  symbol:   class Log
  location: class UnicodeVersion
```