Allow java comment after yylexthrow (#794)
* Reproduce issue #790

```
INFO: Found 2 targets...
ERROR: /Users/regisd/Projects/jflex/javatests/jflex/testcase/yylexthrow_comment/BUILD.bazel:3:6: jflex javatests/jflex/testcase/yylexthrow_comment/Yylexthrow.java failed (Exit 1) jflex_bin failed: error executing command bazel-out/host/bin/jflex/jflex_bin -d bazel-out/darwin-fastbuild/bin/javatests/jflex/testcase/yylexthrow_comment javatests/jflex/testcase/yylexthrow_comment/yylexthrow.flex

Use --sandbox_debug to see verbose messages from the sandbox
Reading "javatests/jflex/testcase/yylexthrow_comment/yylexthrow.flex"

Error in file "javatests/jflex/testcase/yylexthrow_comment/yylexthrow.flex" (line 9):
%yylexthrow needs a list of (qualified) identifiers
%yylexthrow Exception // comment on same line allowed
```

* Allow {EndOfLineComment} after `%yylexthrow`

* Emit the multiple lexer exceptions, one per line
- Add the comment after the exception
- Change type of AbstractLexer.lexThrown from String to List<String>
  Let the emitter do the formatting, instead of concatenating the exceptions in the flex file