Start migration of the testsuite to Bazel (#445)
* Start JFlexTestRunner

  - JflexTestRunner generates code from the lex spec
  - JflexTestRunner verifies that the java code compiles
  - JFlexTestRunner reports javac errors

* Change API of Emitter and LexGenerator to return the generated file [rather than void ; I believe it's a safe API change as a result]

* Add thid_party/junit
  
  Bazel doesn't need it to run tests, but a custom test runner depends on it.

* Migrate `apiprivate` test case
  - Add compile test in ApiPrivate. Without `assertThrows`, the test fails with
    ```
     1) compile(jflex.testcase.apipirivate.ApiPrivateTest)
jflex.testing.exception.CompilerException: javac exception
javac error: yylex() has private access in jflex.testcase.apipirivate.Private, line 10 in file testsuite/javatests/jflex/testcase/apipirivate/AttemptPrivateAccess.java
     ```

* Clean BUILD targets