jflex-maven-plugin test running
3) testTestResources(de.jflex.plugin.maven.JFlexMojoTest)
java.lang.AssertionError: Test project directory does not exist: /private/var/tmp/_bazel_regisd/7163a9e1c27558e3ee879928afc3313e/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/darwin-fastbuild/bin/jflex-maven-plugin/src/test/java/de/jflex/plugin/maven/JFlexMojoTest.runfiles/__main__/src/test/projects/single-file-test
	at org.junit.Assert.fail(Assert.java:88)