Revert "Upgrade JDK to openjdk10"
This reverts commit 6cb2a898b6bd9d0a39db189e0344d532d08891c3.

OpenJDK10 has the same error as OpenJDK9
```
/home/travis/build/jflex-de/jflex/cup-maven-plugin/src/main/java/jflex/maven/plugin/cup/GenerateMojo.java:5: error: cannot access BufferedReader
import java.io.BufferedReader;
              ^
  bad class file: /modules/java.base/java/io/BufferedReader.class
    class file has wrong version 55.0, should be 53.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
1 error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project cup-maven-plugin: Compilation failure -> [Help 1]
```